# Smart Media Converter - Local Startup Script
# Starts Backend + Frontend without Cloudflare tunnels

$ErrorActionPreference = "Continue"
$Script:ProcessIds = @()

function Write-Banner {
    Clear-Host
    Write-Host ""
    Write-Host "  ======================================================================" -ForegroundColor Cyan
    Write-Host "       Smart Media Converter - Local Development Mode                   " -ForegroundColor Cyan
    Write-Host "  ======================================================================" -ForegroundColor Cyan
    Write-Host ""
}

function Write-Step {
    param([string]$Step, [string]$Message)
    Write-Host "  [$Step] " -ForegroundColor Yellow -NoNewline
    Write-Host $Message -ForegroundColor White
}

function Write-Success {
    param([string]$Message)
    Write-Host "  [OK] " -ForegroundColor Green -NoNewline
    Write-Host $Message -ForegroundColor Green
}

function Write-Warn {
    param([string]$Message)
    Write-Host "  [!] " -ForegroundColor Yellow -NoNewline
    Write-Host $Message -ForegroundColor Yellow
}

# Step 1: Cleanup
function Stop-ExistingProcesses {
    Write-Host "  === Step 1: Cleaning Up ===" -ForegroundColor Cyan
    Write-Host ""
    
    Write-Step "1.1" "Stopping existing processes..."
    taskkill /F /IM node.exe 2>$null | Out-Null
    Start-Sleep -Seconds 2
    Write-Success "Cleanup complete"
    Write-Host ""
}

# Step 2: Start Backend
function Start-BackendServer {
    Write-Host "  === Step 2: Starting Backend Server ===" -ForegroundColor Cyan
    Write-Host ""
    
    Write-Step "2.1" "Starting Backend on port 3001 (with hot reload)..."
    $backendPath = "$PSScriptRoot\..\backend"
    
    # Start with nodemon for hot reload
    $proc = Start-Process -FilePath "cmd" -ArgumentList "/c", "cd /d `"$backendPath`" && npm run dev" -PassThru -WindowStyle Minimized
    $Script:ProcessIds += $proc.Id
    
    Write-Step "2.2" "Waiting for Backend (up to 30 seconds)..."
    $maxAttempts = 30
    $attempt = 0
    $ready = $false
    
    while ($attempt -lt $maxAttempts -and -not $ready) {
        Start-Sleep -Seconds 1
        try {
            $response = Invoke-WebRequest -Uri "http://localhost:3001/api/health" -TimeoutSec 2 -UseBasicParsing -ErrorAction SilentlyContinue
            if ($response.StatusCode -eq 200) { $ready = $true }
        }
        catch {
            $attempt++
            if ($attempt % 5 -eq 0) { Write-Host "." -NoNewline }
        }
    }
    Write-Host ""
    
    if ($ready) {
        Write-Success "Backend running on http://localhost:3001"
    }
    else {
        Write-Warn "Backend may still be starting..."
    }
    Write-Host ""
}

# Step 3: Start Frontend
function Start-FrontendServer {
    Write-Host "  === Step 3: Starting Frontend Server ===" -ForegroundColor Cyan
    Write-Host ""
    
    Write-Step "3.1" "Starting Vite on port 8080..."
    $rootPath = "$PSScriptRoot\.."
    
    $proc = Start-Process -FilePath "cmd" -ArgumentList "/c", "cd /d `"$rootPath`" && npm run dev" -PassThru -WindowStyle Minimized
    $Script:ProcessIds += $proc.Id
    
    Write-Step "3.2" "Waiting for Frontend (up to 20 seconds)..."
    $maxAttempts = 20
    $attempt = 0
    $ready = $false
    
    while ($attempt -lt $maxAttempts -and -not $ready) {
        Start-Sleep -Seconds 1
        try {
            $response = Invoke-WebRequest -Uri "http://localhost:8080" -TimeoutSec 2 -UseBasicParsing -ErrorAction SilentlyContinue
            if ($response.StatusCode -eq 200) { $ready = $true }
        }
        catch {
            $attempt++
            if ($attempt % 5 -eq 0) { Write-Host "." -NoNewline }
        }
    }
    Write-Host ""
    
    if ($ready) {
        Write-Success "Frontend running on http://localhost:8080"
    }
    else {
        Write-Warn "Frontend may still be starting..."
    }
    Write-Host ""
}

# Step 4: Reset API Config for Local
function Reset-ApiConfig {
    Write-Host "  === Step 4: Configuring API ===" -ForegroundColor Cyan
    Write-Host ""
    
    Write-Step "4.1" "Setting local API configuration..."
    $configPath = "$PSScriptRoot\..\public\api-config.js"
    $timestamp = [DateTimeOffset]::Now.ToUnixTimeMilliseconds()
    $configContent = @"
/**
 * Runtime API Configuration
 * Auto-generated by start-local.ps1
 * Generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
 */
window.__API_CONFIG__ = {
  backendUrl: null,
  frontendUrl: null,
  timestamp: $timestamp
};
"@
    Set-Content -Path $configPath -Value $configContent -Encoding UTF8
    Write-Success "Local mode configured (uses localhost automatically)"
    Write-Host ""
}

# Step 5: Health Check
function Show-HealthReport {
    Write-Host "  === Step 5: Health Check ===" -ForegroundColor Cyan
    Write-Host ""
    
    Start-Sleep -Seconds 2
    $allHealthy = $true
    
    Write-Step "5.1" "Checking Backend..."
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:3001/api/health" -TimeoutSec 10 -UseBasicParsing
        Write-Success "Backend: OK"
    }
    catch {
        Write-Host "  [X] Backend: NOT responding" -ForegroundColor Red
        $allHealthy = $false
    }
    
    Write-Step "5.2" "Checking Frontend..."
    try {
        $response = Invoke-WebRequest -Uri "http://localhost:8080" -TimeoutSec 10 -UseBasicParsing
        Write-Success "Frontend: OK"
    }
    catch {
        Write-Host "  [X] Frontend: NOT responding" -ForegroundColor Red
        $allHealthy = $false
    }
    
    return $allHealthy
}

# Final Report
function Show-FinalReport {
    param([bool]$AllHealthy)
    
    Write-Host ""
    
    if ($AllHealthy) {
        Write-Host "  ======================================================================" -ForegroundColor Green
        Write-Host "     LOCAL MODE RUNNING SUCCESSFULLY!                                  " -ForegroundColor Green
        Write-Host "  ======================================================================" -ForegroundColor Green
    }
    else {
        Write-Host "  ======================================================================" -ForegroundColor Yellow
        Write-Host "     System started with warnings - Check logs above                   " -ForegroundColor Yellow
        Write-Host "  ======================================================================" -ForegroundColor Yellow
    }
    
    Write-Host ""
    Write-Host "  +--------------------------------------------------------------------+" -ForegroundColor Cyan
    Write-Host "  |                         LOCAL LINKS                                |" -ForegroundColor Cyan
    Write-Host "  +--------------------------------------------------------------------+" -ForegroundColor Cyan
    Write-Host "  |  Frontend:  http://localhost:8080                                  |" -ForegroundColor White
    Write-Host "  |  Backend:   http://localhost:3001/api/health                       |" -ForegroundColor White
    Write-Host "  +--------------------------------------------------------------------+" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  TIP: For public access, run: npm run start:public" -ForegroundColor DarkGray
    Write-Host ""
}

# Cleanup
function Stop-AllServices {
    Write-Host ""
    Write-Host "  Stopping all services..." -ForegroundColor Yellow
    
    foreach ($processId in $Script:ProcessIds) {
        try { Stop-Process -Id $processId -Force -ErrorAction SilentlyContinue } catch {}
    }
    
    taskkill /F /IM node.exe 2>$null | Out-Null
    
    Write-Host "  All services stopped. Goodbye!" -ForegroundColor Green
    Write-Host ""
}

# Main
try {
    Write-Banner
    Stop-ExistingProcesses
    Start-BackendServer
    Start-FrontendServer
    Reset-ApiConfig
    $allHealthy = Show-HealthReport
    Show-FinalReport -AllHealthy $allHealthy
    
    Write-Host "  Press Enter to stop services..." -ForegroundColor Cyan
    Read-Host
}
finally {
    Stop-AllServices
}
